### ISSUE TITLE
Implement Algorand platform

### ISSUE THREAD

**Issue by barnjamin** [wormhole-foundation/connect-sdk#114]
Implement the Algorand platform and TokenBridge protocol

**Comment by SilentRhetoric** [comment]
Planning to take a look at this

**Comment by seichris** [comment]
Looking into it already

**Comment by barnjamin** [comment]
@SilentRhetoric @seichris please consider collaboration if both interested, ultimately only one implementation can be merged 😬 

Please keep this issue updated with progress

**Comment by VKappaKV** [comment]
Hello everyone, looking into this, made any progresses already?

**Comment by SilentRhetoric** [comment]
A PR #151 has been created with a first draft of this implementation.  No tests/examples, yet.

**Comment by SilentRhetoric** [comment]
@cNikolaou @VKappaKV @seichris I invite you to reach out to me via the email address on my GitHub profile so we can discuss potential collaboration.
