### ISSUE TITLE
normalizeAmount fails if decimals is zero

### ISSUE THREAD

**Issue by SilentRhetoric** [wormhole-foundation/connect-sdk#159]
[https://github.com/wormhole-foundation/connect-sdk/blob/ba778599d363c3134f84555154bb9390e072347b/core/base/src/utils/amount.ts#L8](https://github.com/wormhole-foundation/connect-sdk/blob/ba778599d363c3134f84555154bb9390e072347b/core/base/src/utils/amount.ts#L8)

Transfers that supply a token with zero decimals kick out on this 'normalizeAmount' function, which appends ".0" and then thinks that the token has one decimal place.

**Comment by barnjamin** [comment]
fixed in https://github.com/wormhole-foundation/connect-sdk/commit/a5fa7f387837379778e692976a95493684b53990
