### ISSUE TITLE
use with browser wallet

### ISSUE THREAD

**Issue by shunjizhan** [wormhole-foundation/connect-sdk#285]
Hi, I am wondering for `xfer.initiateTransfer(evmSigner)` what's the best way to construct this `evmSigner` from browser wallet (such as metamask)? I saw a [testing helper](https://github.com/wormhole-foundation/connect-sdk/blob/main/platforms/evm/src/testing/signer.ts#L13) that constructs signer from private key, but for browser wallet we don't have access to private key.

Something like these would be super helpful, do similar helpers already exist that I might have missed?
- `getEvmSignerFromEthersWallet(...)`
- `getEvmSignerFromMetamask(...)`

Thanks in advance for the help!

**Comment by barnjamin** [comment]
The `SignAndSendSigner` interface is for this exactly, see this example: https://github.com/barnjamin/ezui

**Comment by barnjamin** [comment]
If the above doesn't satisfy your need, please re-open with comments about what is missing 🙏

**Comment by barnjamin** [comment]
Also just to mention it, the develop branch has a [new type](https://github.com/wormhole-foundation/connect-sdk/blob/develop/core/definitions/src/signer.ts#L63-L83) to allow a sort of "escape hatch"

The Evm implementation will return an `ethers.Signer` (ethers v6) when you call `unwrap` https://github.com/wormhole-foundation/connect-sdk/blob/develop/platforms/evm/src/signer.ts#L35

**Comment by shunjizhan** [comment]
thanks for the examples, super helpful!
